# application-stage.yml (로컬-중간 테스트 개발 환경 설정)
server:
  port: 7000

spring:
  profiles:
    active: health-stage
  datasource:
    url: jdbc:h2:tcp://localhost/~/muscle;MODE=MySQL;DATABASE_TO_UPPER=false
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        show_sql: true
        format_sql: true
