# application-stage.yml (로컬-중간 테스트 개발 환경 설정)
server:
  port: 7000

spring:
  profiles:
    active: health-stage
  datasource:
    url: ${SECRET_URL}
    username: ${SECRET_USERNAME}
    password: ${SECRET_PASSWORD}
    driver-class-name: ${SECRET_DRIVER_CLASS_NAME}
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    generate-ddl: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
