# application-stage.yml (로컬-중간 테스트 개발 환경 설정)
server:
  port: 7000

spring:
  profiles:
    active: health-stage
  datasource:
      url: ${secret_url}
      username: ${env_variables.secret_username}
      password: ${env_variables.secret_password}
      driver-class-name: ${env_variables.secret_driver-class-name}
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    generate-ddl: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
