# application-prod.yml (실제 배포 환경 설정)
server:
  port: 8000

spring:
  datasource:
    url: ${SECRET_URL}
    username: ${SECRET_USERNAME}
    password: ${SECRET_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    generate-ddl: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
