# application-prod.yml (실제 배포 환경 설정)
server:
  port: 8000

spring:
  datasource:
    url: jdbc:mysql://dnd-health.cade1afm85pd.ap-northeast-2.rds.amazonaws.com:3306/dnd-health
    username: admin
    password: dnd12345678
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    generate-ddl: false
    show-sql: false
    properties:
      hibernate:
        format_sql: false

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  sql:
    init:
      mode: never

  security:
    user:
      password: ignored

oauth2:
  kakao:
    infoUrl: https://kapi.kakao.com
    baseUrl: https://kauth.kakao.com
    clientId: 0239e3b799683b851fa867e85be71696
#    redirectUri: https://dnd-9th-4-newple-app.vercel.app/auth
    redirectUri: https://dnd-newple-server.store/api/v1/kakao/signup
    secretKey: ribRjVO6H6cyZ1lztGKxpARTOHfxPGG0
