# application-dev.yml (로컬 개발 환경 설정)
server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/dnd-newple;MODE=MySQL;DATABASE_TO_UPPER=false
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        show_sql: true
        format_sql: true
    defer-datasource-initialization: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  sql:
    init:
      mode: always

oauth2:
  kakao:
    infoUrl: https://kapi.kakao.com
    baseUrl: https://kauth.kakao.com
    clientId: 0239e3b799683b851fa867e85be71696
    redirectUri: http://localhost8080/api/login/oauth2/kakao/result
    secretKey: ribRjVO6H6cyZ1lztGKxpARTOHfxPGG0
